/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.avro;

@SuppressWarnings("all")
public interface HelloService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"HelloService\",\"namespace\":\"com.avro\",\"types\":[{\"type\":\"record\",\"name\":\"Greeting\",\"fields\":[{\"name\":\"greetingMessage\",\"type\":\"string\"}]},{\"type\":\"error\",\"name\":\"GreetingException\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"}]}],\"messages\":{\"hello\":{\"request\":[{\"name\":\"greeting\",\"type\":\"string\"}],\"response\":\"Greeting\",\"errors\":[\"GreetingException\"]}}}");
  com.avro.Greeting hello(java.lang.CharSequence greeting) throws org.apache.avro.AvroRemoteException, com.avro.GreetingException;
}
